language: php
php:
- 7.1
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache/files"
env:
  matrix:
  - SYMFONY_VERSION="3.3.*" DB=sqlite
before-install:
- composer self-update
install:
- composer install -n
#script:
#- "./vendor/bin/simple-phpunit -c phpunit.xml"
deploy:
    provider: script
    script: wget -O /dev/null http://ci.openag.org.uk/app.php?branch=$TRAVIS_BRANCH
    on:
        all_branches: true
notifications:
  email: tobias@neontribe.co.uk
