<?php

namespace OagBundle\Repository;

/**
 * ChangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeRepository extends \Doctrine\ORM\EntityRepository
{
}
