<?php

namespace OagBundle\Repository;

/**
 * EnhancementFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnhancementFileRepository extends \Doctrine\ORM\EntityRepository {

}
