<?php

namespace OagBundle\Repository;

/**
 * RulesetErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RulesetErrorRepository extends \Doctrine\ORM\EntityRepository
{
}
