<?php

namespace OagBundle\Repository;

/**
 * SuggestedSectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestedSectorRepository extends \Doctrine\ORM\EntityRepository {

}
