<?php

namespace OagBundle\Repository;

/**
 * SuggestedTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestedTagRepository extends \Doctrine\ORM\EntityRepository {

}
