imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        charset: UTF8
        driver: pdo_sqlite
        path: '%kernel.project_dir%/app/test.db'

parameters:
    oag_test_assets_directory: '%kernel.project_dir%/tests/OagBundle/Resources/assets'
    oagfiles_directory: '%kernel.project_dir%/web/uploads/tests'
    oagxml_directory: '%kernel.project_dir%/web/xml/tests'
    oag:
        cove:
            cmd: "cat %kernel.project_dir%/tests/OagBundle/Resources/assets/activity-standard-example-annotated.xml"
        classifier:
            text: http://private-044dc3-openag.apiary-mock.com/classifier/plaintext
            xml: 'https://api.foundationcenter.org/v2.0/text/ag_classification/batch'                                                                         
            api_key: gAAAAABaOIerhHq12B4-3OpTQaS4opAyEcqSe01xI20KGL6MDfxgJVjqaNU7YG2Vq0TFv_6lfPu1sr4cP4zazyEvTZg9RfaIDbmjcONL9emtwnVeZtznVfurI8-74_phGkI_QLUJujgjkKr2Vj3aH0PlAn346uK5Bw==            
            threshold: low             
            chunk: true                
            roll_up: true     
    unlink_files: false
