parameters:
    oag:
        cove:
            uri: http://localhost:8008
        geocoder:
            uri: http://localhost:8009
        autogeocoder:
            uri: http://localhost:8010
        dportal:
            uri: http://localhost:8011
        classifier:
            uri: http://gis.foundationcenter.org/OpenAgCoder/extract_codes.php
    oagfiles_directory: '%kernel.project_dir%/web/uploads/oagfiles'
    oagxml_directory: '%kernel.project_dir%/web/xml/oagfiles'
    classifier:
        vocabulary: '99'
        vocabulary_uri: 'http://gis.foundationcenter.org/OpenAgCoder/'
    geocoder:
        id_vocabulary: 'G1'
        admin_1_vocabulary: 'PLACEHOLDER'
        admin_2_vocabulary: 'PLACEHOLDER'
