parameters:
    docker_version: 1.30
    oag:
        cove:
            cmd: docker exec -i --env FILENAME="{FILENAME}" openag_cove /usr/local/bin/process.sh
        geocoder:
            cmd: docker exec -i -e FILENAME="{FILENAME}" -e COUNTRY="{COUNTRY}" openag_geocoder /usr/local/bin/process.sh
        dportal:
            uri: http://SERVER_HOST:8011/ctrack.html?search&year_min=1960&year=1960&year_max=2019&year=2019#view=main
        classifier:
            xml: 'https://api.foundationcenter.org/v2.0/text/ag_classification/batch'
            text: 'https://api.foundationcenter.org/v2.0/text/ag_classification'
            api_key: gAAAAABaOIerhHq12B4-3OpTQaS4opAyEcqSe01xI20KGL6MDfxgJVjqaNU7YG2Vq0TFv_6lfPu1sr4cP4zazyEvTZg9RfaIDbmjcONL9emtwnVeZtznVfurI8-74_phGkI_QLUJujgjkKr2Vj3aH0PlAn346uK5Bw==
            threshold: low
            chunk: true
            roll_up: true
    oagfiles_directory: '%kernel.project_dir%/web/uploads/oagfiles'
    oagxml_directory: '%kernel.project_dir%/web/xml/oagfiles'
    classifier:
        vocabulary: '99'
        vocabulary_uri: 'http://aims.fao.org/standards/agrovoc'
        namespace_uri: 'http://openagfunding.opendataservices.coop/en/latest/extensions/'
    geocoder:
        id_vocabulary: 'G1'
        admin_1_vocabulary: 'PLACEHOLDER'
        admin_2_vocabulary: 'PLACEHOLDER'
    unlink_files: true
    populate_status: false
    docker_reponame: openagdata
    docker_names:
        cove: cove:live
        geocoder: geocoder:live
        nerserver: nerserver:live
        dportal: dportal:live

twig:
    globals:
        show_traceability: false